/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * MAVA API - version 1.0.0
 *
 * API description
 *
 * OpenAPI version: 3.0.3
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.loginUsingGET': ['GET', '/auth/customer/login'],
  'general.loginOutUsingGET': ['GET', '/auth/customer/loginOut'],
  'general.verifyTokenUsingGET': ['GET', '/auth/customer/verify-token']
};
